image: gitlab.myusine.fr:5050/myusine/ops/alpine:latest
deploy:
  environment:
    name: prod
    url: https://dawan.fr
  tags:
    - myusine
  script:
    - echo "deploy"
  rules:
    - if: $CI_COMMIT_TAG
      when: manual